City = str(input("Ingrese el nombre de la ciudad a estudiar: "))
Prec = int(input("Ingrese la precipitación total anual (en mm): "))
Temp = float(input("Ingrese la temperatura media anual (en °C): "))
Ind = Prec / ( Temp + 10)
print ("El índice de Aridez en el municipio de", City, "es de:", Ind)